# Generated by Django 5.2.1 on 2025-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('masuk', 'Surat Masuk'), ('keluar', 'Surat Keluar')], max_length=10)),
                ('nomor_surat', models.CharField(max_length=50, unique=True)),
                ('tanggal', models.DateField()),
                ('pengirim_penerima', models.CharField(max_length=100)),
                ('perihal', models.CharField(max_length=200)),
                ('file_surat', models.FileField(upload_to='surat/')),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
    ]
