# Generated by Django 5.2.1 on 2025-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('keterangan', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipe', models.CharField(choices=[('masuk', 'Kas Masuk'), ('keluar', 'Pengeluaran'), ('denda', 'Denda')], max_length=10)),
            ],
        ),
    ]
