# Generated by Django 5.2.1 on 2025-05-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='jenis',
            field=models.CharField(choices=[('masuk', 'Pemasukan'), ('keluar', 'Pengeluaran')], default=('agenda', 'django_cron', 'dokumentasi', 'forum', 'keuangan'), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='keterangan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='tanggal',
            field=models.DateField(),
        ),
    ]
