# Generated by Django 5.2.1 on 2025-05-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kegiatan', models.CharField(max_length=200)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('lokasi', models.CharField(max_length=200)),
                ('penanggung_jawab', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
    ]
