# Generated by Django 5.2.1 on 2025-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('no_hp', models.CharField(max_length=15)),
                ('alamat', models.TextField()),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('alumni', 'Alumni')], default='aktif', max_length=10)),
                ('tanggal_gabung', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
