# Generated by Django 5.2.1 on 2025-05-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DokumentasiKegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('tanggal', models.DateField()),
                ('deskripsi', models.TextField(blank=True)),
                ('file_foto', models.ImageField(blank=True, null=True, upload_to='dokumentasi/foto/')),
                ('file_video', models.FileField(blank=True, null=True, upload_to='dokumentasi/video/')),
            ],
        ),
    ]
